name: Android-Health

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build Project
        run: ./gradlew assemble
  test:
    needs: build
    runs-on: macOS-latest
    timeout-minutes: 30
    strategy:
      matrix:
        api-level: [21, 23, 29]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86
          disable-animations: true
          profile: Nexus 6
          script: ./gradlew connectedCheck
